# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://joetandurella.github.io'
baseurl: ''
title: 'Joe Tandurella'
description: 'The website for Joe Tandurella
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Biography
  url: /biography/
- title: Research Areas
  url: /research/
- title: Publications
  url: /publications/

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
